
site_name: Armbian Documentation
site_author: "Armbian team"

copyright: Copyright &copy; 2015 - 2022 Armbian team
repo_url: https://github.com/armbian/documentation
repo_name: armbian/documentation

theme: 
    name: material
    custom_dir: overrides
    logo: images/logo.svg
    icon:
      repo: fontawesome/brands/github-alt
    palette:
        - scheme: default
          primary: red
          accent: red
          toggle:
            icon: material/toggle-switch-off-outline 
            name: Switch to dark mode
        - scheme: slate
          primary: red
          accent: red
          toggle:
            icon: material/toggle-switch
            name: Switch to light mode
    favicon: images/logo.png
    features:
        - navigation.tabs
        - navigation.top
        - toc.integrate

extra:
  analytics:
    provider: google
    property: UA-284946-9
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/armbian
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/armbian

plugins:
   - with-pdf:
       author: Armbian documentation team
       copyright: © 2021 by Armbian
       cover_title: Armbian documentation
       cover_subtitle: Linux for ARM development boards

markdown_extensions:
  - smarty
  - footnotes
  - toc:
      permalink: True
  - pymdownx.highlight:
      auto_title: true
      linenums: true
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - 'Board' :
        - 'Maintainers_Procedures_and_Guidelines' : 'Board_Maintainers_Procedures_and_Guidelines.md'
    
  - 'Community' :
        - 'Torrent' : 'Community_Torrent.md'
        - 'IRC' : 'Community_IRC.md'
        - 'Governance' : 'Community_Governance.md'
    
  - 'Developer Guide' :
        - 'Extensions Hooks' : 'Developer-Guide_Extensions-Hooks.md'
        - 'Welcome' : 'Developer-Guide_Welcome.md'
        - 'Build Process' : 'Developer-Guide_Build-Process.md'
        - 'Adding Board Family' : 'Developer-Guide_Adding-Board-Family.md'
        - 'Build Options' : 'Developer-Guide_Build-Options.md'
        - 'Building with Multipass' : 'Developer-Guide_Building-with-Multipass.md'
        - 'Building with Docker' : 'Developer-Guide_Building-with-Docker.md'
        - 'Extensions' : 'Developer-Guide_Extensions.md'
        - 'Testing Procedures' : 'Developer-Guide_Testing-Procedures.md'
        - 'Build Preparation' : 'Developer-Guide_Build-Preparation.md'
        - 'User Configurations' : 'Developer-Guide_User-Configurations.md'
    
  - 'Development Code' :
        - 'Review_Procedures_and_Guidelines' : 'Development-Code_Review_Procedures_and_Guidelines.md'
    
  - 'Hardware' :
        - 'Allwinner' : 'Hardware_Allwinner.md'
        - 'Marvell' : 'Hardware_Marvell.md'
        - 'Allwinner H5 A64' : 'Hardware_Allwinner-H5-A64.md'
        - 'Allwinner H3' : 'Hardware_Allwinner-H3.md'
        - 'Allwinner H6' : 'Hardware_Allwinner-H6.md'
        - 'Freescale imx6' : 'Hardware_Freescale-imx6.md'
        - 'Allwinner A20' : 'Hardware_Allwinner-A20.md'
        - 'Rockchip' : 'Hardware_Rockchip.md'
    
  - 'Process' :
        - 'Contribute' : 'Process_Contribute.md'
        - 'CI' : 'Process_CI.md'
        - 'Merge Policy' : 'Process_Merge-Policy.md'
        - 'Managing_Workflow' : 'Process_Managing_Workflow.md'
        - 'Armbian Task Tracking' : 'Process_Armbian-Task-Tracking.md'
        - 'Release Model' : 'Process_Release-Model.md'
        - 'Documentation' : 'Process_Documentation.md'
    
  - 'Quick' :
        - 'facts' : 'Quick_facts.md'
    
  - 'Release' :
        - 'Board Maintainers' : 'Release_Board-Maintainers.md'
        - 'Changelog' : 'Release_Changelog.md'
    
  - 'User Guide' :
        - 'Getting Started Download Page' : 'User-Guide_Getting-Started-Download-Page.md'
        - 'Advanced Features' : 'User-Guide_Advanced-Features.md'
        - 'Migration_from_Bananian' : 'User-Guide_Migration_from_Bananian.md'
        - 'Networking' : 'User-Guide_Networking.md'
        - 'Armbian Config' : 'User-Guide_Armbian-Config.md'
        - 'Getting Started' : 'User-Guide_Getting-Started.md'
        - 'Board Support Rules' : 'User-Guide_Board-Support-Rules.md'
        - 'Basic Troubleshooting' : 'User-Guide_Basic-Troubleshooting.md'
        - 'FAQ' : 'User-Guide_FAQ.md'
        - 'Allwinner_overlays' : 'User-Guide_Allwinner_overlays.md'
        - 'Recovery' : 'User-Guide_Recovery.md'
        - 'Fine Tuning' : 'User-Guide_Fine-Tuning.md'
        - 'Armbian_overlays' : 'User-Guide_Armbian_overlays.md'
    

